/**
 * generate-sitemap.ts — writes client/public/sitemap.xml from the route
 * manifest and the blog data.
 *
 * WHY THIS IS GENERATED
 * ---------------------
 * The sitemap used to be a hand-edited file, and there were TWO copies of it:
 * client/public/sitemap.xml (the live one, copied into dist by Vite) and
 * public/sitemap.xml. By 2026-09-25 they had drifted apart — the second was
 * missing /tools, /tools/ais-26as-form16 and a blog post, and listed /signup,
 * an auth page nobody should index. The stale copy was deleted and this script
 * replaced both.
 *
 * That drift is the same failure as every other one on this site: a second,
 * hand-maintained copy of something the code already knows, with nothing
 * checking the two agree. Deriving the file removes the possibility rather
 * than fixing one more instance of it.
 *
 * Run: npm run sitemap   (also runs as part of npm run build)
 */
import { writeFileSync, readFileSync } from "fs";
import { resolve } from "path";
import { indexableRoutes } from "../shared/routes";
import { blogPosts } from "../client/src/data/blogPosts";

const ORIGIN = "https://www.aitaxbot.co.in";
const OUT = resolve(import.meta.dirname, "../client/public/sitemap.xml");

/**
 * Priority and change frequency by section. These are hints, not promises, and
 * Google largely ignores them — but a sitemap that claims every page is equally
 * important tells it nothing, so the calculator front door outranks the legal
 * pages here the same way it does in reality.
 */
function weightFor(path: string): { priority: string; changefreq: string } {
  if (path === "/") return { priority: "1.0", changefreq: "weekly" };
  if (path === "/calculators/income-tax") return { priority: "0.95", changefreq: "weekly" };
  if (path.startsWith("/calculators") || path.startsWith("/tools")) return { priority: "0.9", changefreq: "monthly" };
  if (path === "/blog") return { priority: "0.8", changefreq: "weekly" };
  if (path.startsWith("/blog/")) return { priority: "0.7", changefreq: "monthly" };
  if (path.startsWith("/nri")) return { priority: "0.7", changefreq: "monthly" };
  if (["/privacy-policy", "/terms-of-service"].includes(path)) return { priority: "0.3", changefreq: "yearly" };
  return { priority: "0.6", changefreq: "monthly" };
}

const today = new Date().toISOString().slice(0, 10);

type Entry = { path: string; lastmod: string };

const staticEntries: Entry[] = indexableRoutes().map((path) => ({ path, lastmod: today }));

// A post's own dates are better than today's — claiming every article changed
// today is the kind of signal that gets a sitemap ignored.
const blogEntries: Entry[] = blogPosts
  .filter((p: any) => p.status === "published")
  .map((p: any) => ({
    path: `/blog/${p.slug}`,
    lastmod: (p.updatedAt || p.publishedAt || today).slice(0, 10),
  }));

const all = [...staticEntries, ...blogEntries].sort((a, b) => a.path.localeCompare(b.path));

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- GENERATED by scripts/generate-sitemap.ts — do not edit by hand.\n` +
  `     Run: npm run sitemap. Source of truth: shared/routes.ts + blogPosts.ts. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  all
    .map(({ path, lastmod }) => {
      const { priority, changefreq } = weightFor(path);
      return (
        `  <url>\n` +
        `    <loc>${ORIGIN}${path === "/" ? "/" : path}</loc>\n` +
        `    <lastmod>${lastmod}</lastmod>\n` +
        `    <changefreq>${changefreq}</changefreq>\n` +
        `    <priority>${priority}</priority>\n` +
        `  </url>\n`
      );
    })
    .join("") +
  `</urlset>\n`;

// --check compares instead of writing, so CI and the parity test can fail on
// drift without the build quietly rewriting the file under them.
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf-8");
  } catch {
    console.error("sitemap.xml missing — run: npm run sitemap");
    process.exit(1);
  }
  // Ignore lastmod on static pages: it is today's date and would differ on
  // every run. Compare the URL set, which is what actually matters.
  const urls = (s: string) => (s.match(/<loc>[^<]+<\/loc>/g) || []).sort().join("\n");
  if (urls(current) !== urls(xml)) {
    console.error("sitemap.xml is out of date — run: npm run sitemap");
    const a = new Set((current.match(/<loc>([^<]+)<\/loc>/g) || []));
    const b = new Set((xml.match(/<loc>([^<]+)<\/loc>/g) || []));
    for (const u of b) if (!a.has(u)) console.error(`  missing: ${u.replace(/<\/?loc>/g, "")}`);
    for (const u of a) if (!b.has(u)) console.error(`  stale:   ${u.replace(/<\/?loc>/g, "")}`);
    process.exit(1);
  }
  console.log(`sitemap.xml is current (${all.length} URLs).`);
} else {
  writeFileSync(OUT, xml, "utf-8");
  console.log(
    `sitemap.xml written — ${all.length} URLs ` +
    `(${staticEntries.length} pages, ${blogEntries.length} posts).`,
  );
}
